// Copyright (C) 2019  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 19.1 (Build Build 670 09/22/2019)
// Created on Fri May 08 16:52:41 2020

tea_asmd tea_asmd_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst(rst_sig) ,	// input  rst_sig
	.ena(ena_sig) ,	// input  ena_sig
	.start(start_sig) ,	// input  start_sig
	.data(data_sig) ,	// input [63:0] data_sig
	.key(key_sig) ,	// input [127:0] key_sig
	.res(res_sig) ,	// output [63:0] res_sig
	.rdy(rdy_sig) 	// output  rdy_sig
);

